from typing import Literal

SourceKind = Literal[
    "database",
    "warehouse",
    "object_store",
    "saas_app",
    "nosql",
    "stream",
]

EngineKey = Literal[
    "postgresql",
    "mysql",
    "sqlserver",
    "sqlite",
    "oracle",
    "snowflake",
    "bigquery",
    "redshift",
    "s3",
    "azure_blob",
    "databricks_sql",
    "athena",
    "synapse",
    "fabric",
    "trino",
    "dremio",
    "salesforce",
    "mongodb",
    "kafka",
]

# Backwards-compatible alias for older code paths and payloads.
DatabaseType = EngineKey

DATABASE_CATALOG: dict[str, dict] = {
    "postgresql": {
        "key": "postgresql",
        "engine_key": "postgresql",
        "source_kind": "database",
        "label": "PostgreSQL",
        "dialect_label": "PostgreSQL",
        "default_port": 5433,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "localhost",
        "database_placeholder": "demo_db",
        "username_placeholder": "postgres",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Best for the local demo database in this project. Use localhost:5433 on this machine.",
        "ping_sql": "SELECT 1",
        "options": [],
    },
    "mysql": {
        "key": "mysql",
        "engine_key": "mysql",
        "source_kind": "database",
        "label": "MySQL",
        "dialect_label": "MySQL",
        "default_port": 3306,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "localhost",
        "database_placeholder": "mydb",
        "username_placeholder": "root",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Standard MySQL or MariaDB connection using host, port, database, username, and password.",
        "ping_sql": "SELECT 1",
        "options": [],
    },
    "sqlserver": {
        "key": "sqlserver",
        "engine_key": "sqlserver",
        "source_kind": "database",
        "label": "SQL Server",
        "dialect_label": "Microsoft SQL Server",
        "default_port": 1433,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "localhost",
        "database_placeholder": "master",
        "username_placeholder": "sa",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Connect to Microsoft SQL Server with host, port, database, username, and password.",
        "ping_sql": "SELECT 1",
        "options": [],
    },
    "sqlite": {
        "key": "sqlite",
        "engine_key": "sqlite",
        "source_kind": "database",
        "label": "SQLite",
        "dialect_label": "SQLite",
        "default_port": None,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "File Path",
        "host_placeholder": "",
        "database_placeholder": "/path/to/file.db",
        "username_placeholder": "",
        "show_host": False,
        "show_port": False,
        "show_username": False,
        "show_password": False,
        "help_text": "Point directly to a local SQLite database file. Credentials are not required.",
        "ping_sql": "SELECT 1",
        "options": [],
    },
    "oracle": {
        "key": "oracle",
        "engine_key": "oracle",
        "source_kind": "database",
        "label": "Oracle",
        "dialect_label": "Oracle",
        "default_port": 1521,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Service Name",
        "host_placeholder": "localhost",
        "database_placeholder": "FREEPDB1",
        "username_placeholder": "system",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Use the Oracle host, port, and service name for the target database.",
        "ping_sql": "SELECT 1 FROM DUAL",
        "options": [],
    },
    "snowflake": {
        "key": "snowflake",
        "engine_key": "snowflake",
        "source_kind": "warehouse",
        "label": "Snowflake",
        "dialect_label": "Snowflake SQL",
        "default_port": None,
        "host_label": "Account",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "myorg-account123",
        "database_placeholder": "ANALYTICS",
        "username_placeholder": "user_name",
        "show_host": True,
        "show_port": False,
        "show_username": True,
        "show_password": True,
        "help_text": "Use your Snowflake account identifier, not the full Snowsight login page. Warehouse is required.",
        "ping_sql": "SELECT 1",
        "options": [
            {
                "key": "schema",
                "label": "Schema",
                "placeholder": "PUBLIC",
                "required": False,
                "secret": False,
            },
            {
                "key": "warehouse",
                "label": "Warehouse",
                "placeholder": "COMPUTE_WH",
                "required": True,
                "secret": False,
            },
            {
                "key": "role",
                "label": "Role",
                "placeholder": "SYSADMIN",
                "required": False,
                "secret": False,
            },
        ],
    },
    "bigquery": {
        "key": "bigquery",
        "engine_key": "bigquery",
        "source_kind": "warehouse",
        "label": "BigQuery",
        "dialect_label": "GoogleSQL for BigQuery",
        "default_port": None,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Dataset",
        "host_placeholder": "",
        "database_placeholder": "analytics",
        "username_placeholder": "",
        "show_host": False,
        "show_port": False,
        "show_username": False,
        "show_password": False,
        "database_required": False,
        "help_text": "Use a GCP project ID and, if needed, a service account credentials JSON path for BigQuery access.",
        "ping_sql": "SELECT 1",
        "options": [
            {
                "key": "project",
                "label": "Project ID",
                "placeholder": "my-gcp-project",
                "required": True,
                "secret": False,
            },
            {
                "key": "location",
                "label": "Location",
                "placeholder": "US",
                "required": False,
                "secret": False,
            },
            {
                "key": "credentials_path",
                "label": "Credentials JSON Path",
                "placeholder": "/path/to/service-account.json",
                "required": False,
                "secret": False,
            },
        ],
    },
    "redshift": {
        "key": "redshift",
        "engine_key": "redshift",
        "source_kind": "warehouse",
        "label": "Redshift",
        "dialect_label": "Amazon Redshift SQL",
        "default_port": 5439,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "cluster.region.redshift.amazonaws.com",
        "database_placeholder": "dev",
        "username_placeholder": "awsuser",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Use the Redshift cluster or serverless endpoint with database user credentials.",
        "ping_sql": "SELECT 1",
        "options": [],
    },
    "databricks_sql": {
        "key": "databricks_sql",
        "engine_key": "databricks_sql",
        "source_kind": "warehouse",
        "label": "Databricks SQL",
        "dialect_label": "Databricks SQL",
        "default_port": None,
        "host_label": "Server Hostname",
        "port_label": "Port",
        "database_label": "Catalog",
        "host_placeholder": "dbc-a1b2345c-d6e7.cloud.databricks.com",
        "database_placeholder": "main",
        "username_placeholder": "",
        "show_host": True,
        "show_port": False,
        "show_username": False,
        "show_password": True,
        "database_required": False,
        "password_label": "Access Token",
        "help_text": "Use the Server Hostname and HTTP Path from the Databricks SQL warehouse or all-purpose compute JDBC/ODBC settings. Use a personal access token in the password field.",
        "ping_sql": "SELECT 1",
        "options": [
            {"key": "http_path", "label": "HTTP Path", "placeholder": "/sql/1.0/warehouses/...", "required": True, "secret": False},
            {"key": "schema", "label": "Schema", "placeholder": "default", "required": False, "secret": False},
        ],
    },
    "athena": {
        "key": "athena",
        "engine_key": "athena",
        "source_kind": "warehouse",
        "label": "Athena",
        "dialect_label": "Amazon Athena SQL",
        "default_port": None,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "",
        "database_placeholder": "default",
        "username_label": "Access Key ID",
        "password_label": "Secret Access Key",
        "username_placeholder": "AWS_ACCESS_KEY_ID",
        "show_host": False,
        "show_port": False,
        "show_username": True,
        "show_password": True,
        "help_text": "Use AWS credentials plus a region and S3 staging directory. The database field maps to the Athena schema/database.",
        "ping_sql": "SELECT 1",
        "options": [
            {"key": "region", "label": "Region", "placeholder": "us-east-1", "required": True, "secret": False},
            {"key": "s3_staging_dir", "label": "S3 Staging Dir", "placeholder": "s3://my-athena-results/path/", "required": True, "secret": False},
            {"key": "work_group", "label": "Workgroup", "placeholder": "primary", "required": False, "secret": False},
            {"key": "session_token", "label": "Session Token", "placeholder": "Optional AWS session token", "required": False, "secret": True},
        ],
    },
    "synapse": {
        "key": "synapse",
        "engine_key": "synapse",
        "source_kind": "warehouse",
        "label": "Synapse",
        "dialect_label": "Azure Synapse SQL",
        "default_port": 1433,
        "host_label": "Server",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "workspace.sql.azuresynapse.net",
        "database_placeholder": "dedicated_pool",
        "username_placeholder": "sql_user",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Synapse SQL uses a SQL Server compatible TDS endpoint over port 1433.",
        "ping_sql": "SELECT 1",
        "options": [],
    },
    "fabric": {
        "key": "fabric",
        "engine_key": "fabric",
        "source_kind": "warehouse",
        "label": "Fabric",
        "dialect_label": "Microsoft Fabric Warehouse SQL",
        "default_port": 1433,
        "host_label": "TDS Endpoint",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "yourwarehouse.datawarehouse.fabric.microsoft.com",
        "database_placeholder": "Warehouse",
        "username_placeholder": "sql_user",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Fabric Warehouse is exposed through a SQL Server compatible TDS endpoint over port 1433.",
        "ping_sql": "SELECT 1",
        "options": [],
    },
    "trino": {
        "key": "trino",
        "engine_key": "trino",
        "source_kind": "warehouse",
        "label": "Trino",
        "dialect_label": "Trino SQL",
        "default_port": 8080,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Catalog",
        "host_placeholder": "trino.example.com",
        "database_placeholder": "hive",
        "username_placeholder": "trino_user",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Use Trino host, port, username, catalog, and optional schema. Password is used for basic auth when enabled.",
        "ping_sql": "SELECT 1",
        "options": [
            {"key": "schema", "label": "Schema", "placeholder": "default", "required": False, "secret": False},
            {"key": "http_scheme", "label": "HTTP Scheme", "placeholder": "https", "required": False, "secret": False},
        ],
    },
    "dremio": {
        "key": "dremio",
        "engine_key": "dremio",
        "source_kind": "warehouse",
        "label": "Dremio",
        "dialect_label": "Dremio SQL",
        "default_port": None,
        "host_label": "API Base URL",
        "port_label": "Port",
        "database_label": "Project ID",
        "host_placeholder": "https://api.dremio.cloud",
        "database_placeholder": "project-id",
        "username_placeholder": "",
        "show_host": True,
        "show_port": False,
        "show_username": False,
        "show_password": True,
        "password_label": "Access Token",
        "help_text": "Use a Dremio Cloud API base URL and personal access token. Project ID is used for catalog discovery.",
        "ping_sql": "SELECT 1",
        "options": [],
    },
    "s3": {
        "key": "s3",
        "engine_key": "s3",
        "source_kind": "object_store",
        "label": "Amazon S3",
        "dialect_label": "DuckDB SQL over S3 files",
        "default_port": None,
        "host_label": "Bucket",
        "port_label": "Port",
        "database_label": "Prefix",
        "host_placeholder": "my-bucket",
        "database_placeholder": "folder/path/",
        "username_label": "Access Key ID",
        "password_label": "Secret Access Key",
        "username_placeholder": "AWS_ACCESS_KEY_ID",
        "show_host": True,
        "show_port": False,
        "show_username": True,
        "show_password": True,
        "database_required": False,
        "help_text": "Connect to an S3 bucket and treat matching CSV, JSON, or Parquet files as a virtual table. Region is required.",
        "ping_sql": "SELECT 1",
        "options": [
            {
                "key": "region",
                "label": "Region",
                "placeholder": "us-east-1",
                "required": True,
                "secret": False,
            },
            {
                "key": "session_token",
                "label": "Session Token",
                "placeholder": "Optional AWS session token",
                "required": False,
                "secret": True,
            },
            {
                "key": "endpoint_url",
                "label": "Endpoint URL",
                "placeholder": "Optional custom endpoint",
                "required": False,
                "secret": False,
            },
            {
                "key": "file_format",
                "label": "File Format",
                "placeholder": "auto | parquet | csv | json",
                "required": False,
                "secret": False,
            },
            {
                "key": "table_name",
                "label": "Table Name",
                "placeholder": "events",
                "required": False,
                "secret": False,
            },
        ],
    },
    "azure_blob": {
        "key": "azure_blob",
        "engine_key": "azure_blob",
        "source_kind": "object_store",
        "label": "Azure Blob",
        "dialect_label": "DuckDB SQL over Azure Blob files",
        "default_port": None,
        "host_label": "Account URL",
        "port_label": "Port",
        "database_label": "Container",
        "host_placeholder": "https://myaccount.blob.core.windows.net",
        "database_placeholder": "my-container",
        "username_placeholder": "",
        "show_host": True,
        "show_port": False,
        "show_username": False,
        "show_password": False,
        "help_text": "Connect to Azure Blob Storage and treat matching CSV, JSON, or Parquet files as a virtual table. Provide either a connection string or account URL plus SAS or account key.",
        "ping_sql": "SELECT 1",
        "options": [
            {
                "key": "prefix",
                "label": "Blob Prefix",
                "placeholder": "folder/path/",
                "required": False,
                "secret": False,
            },
            {
                "key": "connection_string",
                "label": "Connection String",
                "placeholder": "DefaultEndpointsProtocol=...",
                "required": False,
                "secret": True,
            },
            {
                "key": "sas_token",
                "label": "SAS Token",
                "placeholder": "?sv=...",
                "required": False,
                "secret": True,
            },
            {
                "key": "account_name",
                "label": "Account Name",
                "placeholder": "myaccount",
                "required": False,
                "secret": False,
            },
            {
                "key": "account_key",
                "label": "Account Key",
                "placeholder": "Base64 account key",
                "required": False,
                "secret": True,
            },
            {
                "key": "file_format",
                "label": "File Format",
                "placeholder": "auto | parquet | csv | json",
                "required": False,
                "secret": False,
            },
            {
                "key": "table_name",
                "label": "Table Name",
                "placeholder": "blob_rows",
                "required": False,
                "secret": False,
            },
        ],
    },
    "salesforce": {
        "key": "salesforce",
        "engine_key": "salesforce",
        "source_kind": "saas_app",
        "label": "Salesforce",
        "dialect_label": "Salesforce SOQL",
        "default_port": None,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Object",
        "host_placeholder": "",
        "database_placeholder": "Account",
        "username_placeholder": "user@example.com",
        "show_host": False,
        "show_port": False,
        "show_username": True,
        "show_password": True,
        "database_required": False,
        "help_text": "Use Salesforce username, password, and security token. The database field can scope schema/query work to a specific object like Account or Opportunity.",
        "ping_sql": "SELECT 1",
        "options": [
            {"key": "security_token", "label": "Security Token", "placeholder": "Salesforce security token", "required": True, "secret": True},
            {"key": "domain", "label": "Domain", "placeholder": "login | test", "required": False, "secret": False},
        ],
    },
    "mongodb": {
        "key": "mongodb",
        "engine_key": "mongodb",
        "source_kind": "nosql",
        "label": "MongoDB",
        "dialect_label": "DuckDB SQL over sampled MongoDB documents",
        "default_port": 27017,
        "host_label": "Host",
        "port_label": "Port",
        "database_label": "Database",
        "host_placeholder": "localhost",
        "database_placeholder": "sample_mflix",
        "username_placeholder": "mongo_user",
        "show_host": True,
        "show_port": True,
        "show_username": True,
        "show_password": True,
        "help_text": "Connect to MongoDB, sample collection documents, and query them through temporary DuckDB views.",
        "ping_sql": "SELECT 1",
        "options": [
            {"key": "collection", "label": "Collection", "placeholder": "movies", "required": False, "secret": False},
            {"key": "sample_size", "label": "Sample Size", "placeholder": "200", "required": False, "secret": False},
        ],
    },
    "kafka": {
        "key": "kafka",
        "engine_key": "kafka",
        "source_kind": "stream",
        "label": "Kafka",
        "dialect_label": "DuckDB SQL over sampled Kafka messages",
        "default_port": 9092,
        "host_label": "Bootstrap Servers",
        "port_label": "Port",
        "database_label": "Topic",
        "host_placeholder": "localhost:9092",
        "database_placeholder": "events",
        "username_placeholder": "",
        "show_host": True,
        "show_port": False,
        "show_username": False,
        "show_password": False,
        "help_text": "Connect to Kafka, sample JSON messages from a topic, and query them through temporary DuckDB views.",
        "ping_sql": "SELECT 1",
        "options": [
            {"key": "topic", "label": "Topic Override", "placeholder": "Optional topic override", "required": False, "secret": False},
            {"key": "group_id", "label": "Group ID", "placeholder": "ai-data-middleware", "required": False, "secret": False},
            {"key": "sample_size", "label": "Sample Size", "placeholder": "100", "required": False, "secret": False},
            {"key": "auto_offset_reset", "label": "Auto Offset Reset", "placeholder": "latest | earliest", "required": False, "secret": False},
        ],
    },
}


def get_database_definition(engine_key: str) -> dict:
    db_def = DATABASE_CATALOG.get(engine_key)
    if not db_def:
        supported = ", ".join(DATABASE_CATALOG)
        raise ValueError(f"Unsupported source engine '{engine_key}'. Supported types: {supported}.")
    return db_def


def get_database_catalog() -> list[dict]:
    return list(DATABASE_CATALOG.values())


def get_ping_sql(engine_key: str) -> str:
    return get_database_definition(engine_key).get("ping_sql", "SELECT 1")


def resolve_source_config(
    source_kind: str | None = None,
    engine_key: str | None = None,
    db_type: str | None = None,
) -> tuple[str, str]:
    resolved_engine_key = (engine_key or db_type or "postgresql").strip()
    meta = get_database_definition(resolved_engine_key)
    resolved_source_kind = (source_kind or meta["source_kind"]).strip()

    if resolved_source_kind != meta["source_kind"]:
        raise ValueError(
            f"Source kind '{resolved_source_kind}' does not match engine '{resolved_engine_key}'. "
            f"Expected '{meta['source_kind']}'."
        )

    return resolved_source_kind, resolved_engine_key
